version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/code/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/code/frontend"
    schedule:
      interval: "weekly"
