spring.application.name=usersmanagementsystem
# spring.datasource.url=jdbc:mysql://localhost:3306/hrmsdb?createDatabaseIfNotExist=true&useSSL=true
# spring.datasource.username=root
# spring.datasource.password=ROOT

spring.datasource.url=jdbc:mysql://64.227.128.119:3306/hrmstestdb?createDatabaseIfNotExist=true&useSSL=true
spring.datasource.username=hrms_test
spring.datasource.password=rooT@3225

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=1010

# Hibernate Properties
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework=INFO
logging.level.com.phegondev=DEBUG

# Jackson Properties
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.default-property-inclusion=non-null

# SMTP Configuration for Sending Emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587 
#spring.mail.username=suryprakash513@gmail.com
#spring.mail.password=rjzi hdgr ydmf zbtk
spring.mail.username=nevoinfi@gmail.com
spring.mail.password=knys szgf fsuz rcgv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mailersend.api.key=mlsn.9aa04471c7166884f5edd94c3f180d51310ed87b721ee32524498237387f5f50
mailersend.from.email=superadmin@infinevocloud.com
mailersend.from.name=nevoinfi

#brevo.api.key=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
#brevo.from.email=info@infinevocloud.com
#brevo.from.name=nevoinfi

# ==============================
# BREVO (Sendinblue) API CONFIG
# ==============================

brevo.api.key=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
brevo.from.email=payrollnevoinfi@gmail.com
brevo.from.name=Infinevo HRMS


# cloudinary config
cloudinary.cloud_name=dthv5gvff
cloudinary.api_key=214156656966532
cloudinary.api_secret=Dr7flou_EEr38ZN0eWvLwSi9dCw


security.api.key=12345AB