/**
 * Mock data for Admin Reimbursement Management page.
 *
 * Fields match the future GET /admin/reimbursements API response.
 * Replace this array with the actual API response when backend is ready.
 */
const mockAdminReimbursements = [
  {
    id: 1,
    employeeId: "EMP001",
    employeeNumber: "EMP-001",
    employeeName: "John Mathew",
    reimbursementType: "Medical",
    description: "Medicine Bills for hospitalization",
    requestedAmount: 5000,
    approvedAmount: null,
    status: "PENDING",
    requestDate: "05-Aug-2026",
    billDate: "05-Aug-2026",
    reimbursementMonth: "2026-08",
    remarks: null,
    paymentStatus: "UNPAID",
    attachmentUrl: "medicine_bill.pdf",
  },
  {
    id: 2,
    employeeId: "EMP002",
    employeeName: "Rahul Sharma",
    reimbursementType: "Travel",
    description: "Client Visit – Pune to Mumbai",
    requestedAmount: 3000,
    approvedAmount: 2500,
    status: "APPROVED",
    requestDate: "01-Aug-2026",
    billDate: "01-Aug-2026",
    remarks: "Eligible amount approved",
    paymentStatus: "UNPAID",
    attachmentUrl: "travel_bills.pdf",
  },
  {
    id: 3,
    employeeId: "EMP003",
    employeeName: "Ali Hassan",
    reimbursementType: "Medical",
    description: "Hospital Bills – Emergency",
    requestedAmount: 7500,
    approvedAmount: null,
    status: "PENDING",
    requestDate: "03-Aug-2026",
    billDate: "03-Aug-2026",
    remarks: null,
    paymentStatus: "UNPAID",
    attachmentUrl: "hospital_bills.pdf",
  },
  {
    id: 4,
    employeeId: "EMP004",
    employeeName: "Priya Nair",
    reimbursementType: "Internet",
    description: "Broadband bill – July 2026",
    requestedAmount: 999,
    approvedAmount: 999,
    status: "APPROVED",
    requestDate: "20-Jul-2026",
    billDate: "20-Jul-2026",
    remarks: "Approved as per policy",
    paymentStatus: "PAID",
    attachmentUrl: null,
  },
  {
    id: 5,
    employeeId: "EMP005",
    employeeName: "Deepak Verma",
    reimbursementType: "Food",
    description: "Team lunch during client meeting",
    requestedAmount: 1500,
    approvedAmount: null,
    status: "REJECTED",
    requestDate: "25-Jul-2026",
    billDate: "25-Jul-2026",
    remarks: "Not as per policy",
    paymentStatus: "UNPAID",
    attachmentUrl: null,
  },
  {
    id: 6,
    employeeId: "EMP006",
    employeeName: "Sneha Kulkarni",
    reimbursementType: "Fuel",
    description: "Fuel expenses for client site visits",
    requestedAmount: 2200,
    approvedAmount: null,
    status: "PENDING",
    requestDate: "02-Aug-2026",
    billDate: "02-Aug-2026",
    remarks: null,
    paymentStatus: "UNPAID",
    attachmentUrl: "fuel_receipts.pdf",
  },
  {
    id: 7,
    employeeId: "EMP007",
    employeeName: "Arjun Patel",
    reimbursementType: "Travel",
    description: "Train fare for branch office visit",
    requestedAmount: 1800,
    approvedAmount: 1800,
    status: "APPROVED",
    requestDate: "28-Jul-2026",
    billDate: "28-Jul-2026",
    remarks: "Fully approved",
    paymentStatus: "PAID",
    attachmentUrl: "train_ticket.pdf",
  },
  {
    id: 8,
    employeeId: "EMP008",
    employeeName: "Kavita Singh",
    reimbursementType: "Medical",
    description: "Dental treatment",
    requestedAmount: 4000,
    approvedAmount: null,
    status: "PENDING",
    requestDate: "04-Aug-2026",
    billDate: "04-Aug-2026",
    remarks: null,
    paymentStatus: "UNPAID",
    attachmentUrl: "dental_bill.pdf",
  },
];

export default mockAdminReimbursements;
