-- Seed: the three dev users' tenant memberships.
--
-- Local development only. Not a Flyway migration, and never run against a deployed
-- environment — seed.sh says the same thing and is the only thing that runs this file.
--
-- Idempotent: re-running changes nothing. V002__user_tenant.sql:17 puts a unique index on
-- (user_id, tenant_id), so ON CONFLICT DO NOTHING is enough. `id` is left to the table
-- default rather than pinned, because nothing references a membership row by id.
--
-- The user UUIDs are NOT generated here and NOT generated by Keycloak either. They are
-- pinned on each user in infra/docker/keycloak/dev-realm.json, and these are the same
-- three values. Keycloak mints a fresh UUID per user at import unless "id" is set, and a
-- fresh UUID would leave every token's `sub` pointing at no membership row — which
-- TenantContextFilter answers with 401 TENANT_NOT_BOUND. If you edit a user's id in the
-- realm export, edit it here in the same commit, or local login stops working.
--
--   a0000000-…-0001  admin.acme        -> Acme Manufacturing  (11111111-…)
--   b0000000-…-0001  admin.globex      -> Globex Corporation  (22222222-…)
--   b0000000-…-0002  employee.globex   -> Globex Corporation  (22222222-…)
--
-- The `a` / `b` prefix is the tenant the user belongs to, readable at a glance and
-- deliberately unlike the tenant UUIDs themselves so the two are never confused in a log.
--
-- Every user here belongs to exactly one tenant. That is a limit worth knowing about: the
-- X-Tenant-Id header path in TenantAuthenticationExtractor, which lets a multi-tenant user
-- choose, has nothing to exercise it locally. Adding a second row for admin.globex would
-- cover it — and would also stop single-tenant auto-binding being exercised. Leave it at
-- one until a ticket needs the other case.

INSERT INTO core.user_tenant (tenant_id, user_id, created_by, updated_by) VALUES
    ('11111111-1111-1111-1111-111111111111', 'a0000000-0000-0000-0000-000000000001', 'seed', 'seed'),
    ('22222222-2222-2222-2222-222222222222', 'b0000000-0000-0000-0000-000000000001', 'seed', 'seed'),
    ('22222222-2222-2222-2222-222222222222', 'b0000000-0000-0000-0000-000000000002', 'seed', 'seed')
ON CONFLICT (user_id, tenant_id) DO NOTHING;

SELECT format('seed 02-user-tenants: %s membership(s) present', count(*)) AS status FROM core.user_tenant;
