package com.itsdev.payroll.dto.leaveAndAttendance;

import java.util.List;

public class LeaveTypeResponse {
    private int code;
    private String message;
    private LeaveTypeDTO leave;
    private List<LeaveTypeDTO> leaves;

    public LeaveTypeResponse(int code, String message, LeaveTypeDTO leave) {
        this.code = code;
        this.message = message;
        this.leave = leave;
    }

    public LeaveTypeResponse(int code, String message, List<LeaveTypeDTO> leaves) {
        this.code = code;
        this.message = message;
        this.leaves = leaves;
    }

    public LeaveTypeResponse(int code, String message) {
        this.code = code;
        this.message = message;
    }

    // getters and setters will be generated by IDE


    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public LeaveTypeDTO getLeave() {
        return leave;
    }

    public void setLeave(LeaveTypeDTO leave) {
        this.leave = leave;
    }

    public List<LeaveTypeDTO> getLeaves() {
        return leaves;
    }

    public void setLeaves(List<LeaveTypeDTO> leaves) {
        this.leaves = leaves;
    }
}

