spring.application.name=Payroll
 
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Disable Spring Boot's default snake_case naming
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
 
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://authentication.infinevocloud.com/realms/HRMS
 
# Keycloak Admin Configuration for creating users via Admin API on Docker
keycloak.admin.server-url=https://authentication.infinevocloud.com
keycloak.admin.realm=HRMS
keycloak.admin.client-id=hrms-payroll-backend
keycloak.admin.client-secret=G9ccmvOROhVK3JYNqy5vhMtfwVjCtUo6
keycloak.admin.username=admin
keycloak.admin.password=admin@123
 
 
# cloudinary config
cloudinary.cloud_name=dbsu0ghks
cloudinary.api_key=416592267625392
cloudinary.api_secret=k-sUKDxLB2U9TQE92A53k3wXqaE
 

# Scheduler Configuration
spring.task.scheduling.pool.size=5
 
# Enable scheduler
spring.task.scheduling.enabled=true
 
# # Using Brevo (formerly Sendinblue) SMTP
# brevo.api.key=xsmtpsib-ad278ff805e15341fc4ce7178e040eb3491e544a1ad695188e6c80bc6e7ef4ae-P7nLCVV5R3UNfSqe
# brevo.from.email=bprasad@infinevocloud.com
# brevo.from.name=HRMS Payroll
# brevo.api.url=https://api.brevo.com/v3/smtp/email
 
# brevo.template.poi.reminder=5
 
 
# Brevo Configuration
brevo.api.key=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
brevo.api.url=https://api.brevo.com/v3/smtp/email
brevo.email.sender.name=Infinevo Payroll
brevo.email.sender.email=payrollnevoinfi@gmail.com
 
# IT Declaration Email Templates
brevo.template.poi.reminder=5
brevo.template.itdeclaration.reminder=6
brevo.template.itdeclaration.lock=7
brevo.template.poi.submission=8
brevo.template.itdeclaration.release=9
brevo.template.salary.slip=10

# Invitation Template (same for both users and employees)
brevo.template.employee.invitation=15
brevo.template.user.invitation=20

# Credentials Templates (separate)
brevo.template.employee.credentials=18
brevo.template.user.credentials=19

fed.secret=payroll-fed-secret-123

app.portal.base-url=https://mypayroll.infinevocloud.com