
#spring.datasource.url=jdbc:mysql://64.227.128.119:3306/payroll_test_db?createDatabaseIfNotExist=true&useSSL=true
#spring.datasource.username=hrms_test
#spring.datasource.password=rooT@3225

 spring.datasource.url=jdbc:mysql://157.245.96.121:3306/payroll_test_db?createDatabaseIfNotExist=true&useSSL=true
 spring.datasource.username=hrms_user
 spring.datasource.password=Str0ngP@ss!

server.port=3043

api.base.url=https://myhrms.infinevocloud.com/
app.portal.base-url=https://mypayroll.infinevocloud.com

frontend.base-url=https://non-prod-payroll.infinevocloud.com

api.key=12345AB
